name: 'Deploy'

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          echo "Deploying to production..."
          echo "Deployed successfully!"